### ISSUE TITLE
Project incomplete, and therefore does not build

### ISSUE THREAD

**Issue by DatBlaueHus** [eleev/swiftui-new-metal-shaders#1] opened 2023-11-28 16:27 UTC
Declared, but not defined in the project:
EmptyVisualEffect.rotation3D, and probably related to it .degrees

Also, in ComplexWaveView line 53 the 'ComplexWaveController' is inaccessible due to 'private' protection level, and therefore can not be extended/observed.

**Comment by jVirus** [comment] 2023-12-01 08:01
@DatBlaueHus  Thank you for bringing these issues up.


1. The issue is that the `EmptyVisualEffect.rotation3D` was renamed by Apple to `EmptyVisualEffect.rotation3DEffect`. There are a couple of places where this refactoring needs to be applied. 
2. The other issue can be easily solved by moving the `ComplexWaveController ` out of the enclosing type.

With these two refactorings in place project is complete and can be easily built.  You are welcome to propose these changes in a pull request.

**Comment by eleev** [comment] 2024-05-23 07:19
@DatBlaueHus thank you for opening this issue! It was resolved in #2

**Closed as completed by eleev** 2024-05-23 07:19 UTC
